version: "3.7"

volumes: #definimos los volumenes del sistema
    postgres_data:

services:
    postgres:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/posgresql/postgres_data #Compartimos los datos de posgres al volumen del sistema, esta ruta viene en la documentación de la imagén
            - ./db/init:/docker-entrypoint-initdb.d
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: 123456789